language: python
python:
  - "2.7"
before_install:
  - pip install requests
  
install:

script:
  - python semaphore_xecute.py building
  - python helloworld.py
after_success:
  - python semaphore_xecute.py success
after_failure:
  - python semaphore_xecute.py failure